name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
        with:
          fetch-depth: 0
      - name: Install JDK ${{ matrix.java_version }}
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 17
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@main
        with:
          configuration: ".github/changelog-configuration.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Get the version
        id: tagger
        uses: jimschubert/query-tag-action@v2
        with:
          skip-unshallow: 'true'
          abbrev: false
          commit-ish: HEAD
      - name: Install Android SDK
        uses: malinskiy/action-android/install-sdk@release/0.1.4
      - name: Build project
        run: ./gradlew assembleRelease
        env:
          VERSION: ${{steps.tagger.outputs.tag}}
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{steps.tagger.outputs.tag}}
          generate_release_notes: true
          name: ${{steps.tagger.outputs.tag}}
          body: ${{steps.github_release.outputs.changelog}}
          files: |
            mobilevision-pipeline/build/outputs/aar/mobilevision-pipeline-release.aar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
