name: "Validate Gradle Wrapper"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
      - uses: gradle/wrapper-validation-action@v3
